version: '3'


networks:
    laravel:
        driver: bridge

services:
    app:
        hostname: app
        build:
            context: ./docker/local/nginx
            dockerfile: ./Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${APP_PORT}:80"
        networks:
            - laravel
        volumes:
            - .:/var/www/html:delegated
        depends_on:
            - node
            - php
            - pgsql
    pgsql:
        hostname: pgsql
        image: postgres:16.2-alpine
        ports:
            - "${DB_PORT}:5432"
        networks:
            - laravel
        environment:
            POSTGRES_DB: ${DB_DATABASE:-cats-app}
            POSTGRES_USER: ${DB_USERNAME:-pgsql}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}

    php:
        hostname: php
        build:
            context: ./docker/local/php-fpm
            dockerfile: ./Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        networks:
            - laravel
        volumes:
            - .:/var/www/html:delegated

    node:
        hostname: node
        image: node:21-alpine
        build:
            context: ./docker/local/node
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        networks:
            - laravel
        tty: true

    composer:
        build:
            context: ./docker/local/php-fpm
            dockerfile: ./Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html
        depends_on:
            - php
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    artisan:
        build:
            context: ./docker/local/php-fpm
            dockerfile: ./Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html
        depends_on:
            - pgsql
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - laravel
    npm:
        image: node:21-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "3000:3000"
            - "3001:3001"
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]

